spring:
    application:
        name: seguimientoProyectosBackUp
    datasource:
        url: jdbc:mysql://localhost:3306/seguimiento_proyectos?dropDatabaseIfExist=true&createDatabaseIfNotExist=true
        username: root
        password: infinity
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        show-sql: off
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
        open-in-view: true
    data:
        jpa:
            repositories:
                enabled: true